### ISSUE TITLE
trex-emu socket creation 

### ISSUE THREAD

**Issue by janrodson** [cisco-system-traffic-generator/trex-emu#11]
Hi!

I´m trying to develop an emu plugin for GTP traffic. The plugin itself creates the session request packets, sends them to the DUT and gets the responses to process the packets.

The main issue and reason for this post is that the response packets are not getting forwarded from the trex-core back to the trex-emu. I´ve used the example  [7.2 Transport layer](https://trex-tgn.cisco.com/trex/doc/trex_emu.html#_transport_layer) and also the [transport_example](https://github.com/cisco-system-traffic-generator/trex-emu/blob/master/src/emu/plugins/transport_example/example.go) plugin provided with the code since the traffic we want to be sent to emu (GTP create session response) is UDP with src and dst ports 2123.

I made some captures to check the route of the packets, one in the zmq channel between emu and core and one in each of the tx and rx ports of the core also. As expected, the requests packets reach the DUT and create the sessions and the responses come back to the server. Once here, the responses are not getting forwarded to emu and I suspect it is because my implementation of the socket creation on my plugin.

[This](https://user-images.githubusercontent.com/89969132/131823842-389c5527-7b4f-43e7-91b7-f040e4e4292a.png) is a part of the capture done in the rx of the core with one of the packets I want to be forwarded to trex-emu. The 5.0.0.1 is the DUT IP and the 6.12.0.X are the clients IPs.

My first approach was to create a socket for each emu client so I added this "createSocketPerClient" function to the OnEvent callback.

        func (o *PluginGtpcClient) OnEvent(msg string, a, b interface{}) {
        
	        f, _ := os.OpenFile("trace.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
        
	        switch msg {
	        case core.MSG_DG_MAC_RESOLVED:
		        bitMask, ok := a.(uint8)
		        if !ok {
			        // failed at type assertion
			        return
		        }
        
		        resolvedIPv4 := (bitMask & core.RESOLVED_IPV4_DG_MAC) == core.RESOLVED_IPV4_DG_MAC
		        if resolvedIPv4 {
			        myIPv4 := o.Client.Ipv4
			        if myIPv4[0] == 11 && myIPv4[1] == 0 {
				        return
			        }
			        f.WriteString("Going to create a socket\n")
			        o.createSocketPerClient() //Prepares and creates the socket
        
			        o.sendGtpcCSRPacket() //Send the connection request
			        o.startTimer() //Periodical timer to send echo requests
		        }
	        }
        }

The socket created is "clientIP:2123" for UDP traffic

        func (o *PluginGtpcClient) createSocketPerClient() {
        
	        f, _ := os.OpenFile("trace.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	        f.WriteString("\tAcquiring the transport ctx\n")
        
	        o.ctx = transport.GetTransportCtx(o.Client) //Get the plugin or thread ctx?
        
	        clientIP := o.Client.Ipv4
	        var gtpPort = "2123"
	        var clientIPby = net.IPv4(clientIP[0], clientIP[1], clientIP[2], clientIP[3])
	        var socket = clientIPby.String() + ":" + gtpPort
        
	        f.WriteString("\tDialing socket: " + socket + "\n")
        
	        s, err := o.ctx.Dial("udp", socket, o, nil, nil, 2123)
	        if err != nil {
		        f.WriteString("\tERROR creating the socket \n")
		        return
	        }
	        o.s = s
	        f.WriteString("\tSocket " + s.LocalAddr().String() + " created succesfully --> LOCAL \n")
	        f.WriteString("\tSocket " + s.RemoteAddr().String() + " created succesfully --> REMOTE\n\n")
        }

I put this log messages to check the creation process and as shown [here](https://user-images.githubusercontent.com/89969132/131821244-e075c27d-ce83-4c5d-9163-af8534bb8ff9.png) for example, it seems correct, there isn´t any error and it gets to the end. 

    Going to create a socket
            Acquiring the transport ctx
            Dialing socket: 6.12.0.11:2123
            Socket 6.12.0.11:2123 created succesfully --> LOCAL
            Socket 6.12.0.11:2123 created succesfully --> REMOTE

I´ve implemented the rest of the callbacks (OnRxEvent, OnRxData and OnTxEvent) also with log messages just for debugging purpose but as said before, the packets aren´t reaching emu, that´s why I think the problem is in the socket creation.

I don´t know if this approach of having one socket per client is viable or if is there a way to create a generic socket for all traffic coming to 2123 port (some kind of 0.0.0.0:2123). Without anything else to add, I appreciate any help. Thanks!

**Comment by hhaim** [comment]
@janrodson   make sure the service filter mode is enabled with  TRANSPORT MASK 
[code](https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/api/client_code.html?highlight=service#trex.stl.trex_stl_client.STLClient.set_service_mode_base
)
the filter move packets with this criteria 
```(src_port & 0xff00 == 0xff00) ``` to EMU. try to capture to verify that the DUT does not change it

I would move to one core with trex-server ( ```-c 1 --software```) to reduce the filter mode

```mDNS``` work on top of transport layer.

**Comment by janrodson** [comment]
@hhaim first of all thanks for your response.

I saw it and I have been trying some things. If filter mode is activated and dial the sockets "ClientIP:65280", I can see the responses through the zmq channel and also the packets seem correct, but anyways the callbacks are not getting triggered anytime.

In my tests I use 10 clients, I displayed the transport counters and that is what I saw:

             name       | value 
        ----------------+------
        ft_new_udp      | 10    
        ft_new_no_cb*   | 10    
        dial            | 1     
        src_port_alloc  | 1     
        src_port_active | 1     
        ft_addv4        | 1     
        ft_activev4     | 1     
        ft_lookupv4     | 10  

As I interpret, I´m creating 10 new udp flows but also any of them has any callback associated so I guess something is not going correctly in the socket creation process.

Also I kept troubleshooting and putting more logs in here and there. In HandleRxUdpNewFlow, in the line:

    acceptCb := o.lookupServerPort(dstport, UDP_PROTO)

I get everytime nil and that is because "o.serverCb" is empty.

Last but not least, just remember that the main goal of my socket creation is to get the GTP-C response packets to emu and get some info of them. Thanks again for your help.

**Comment by bdollma** [comment]
Hi @janrodson ,
Your problem happens because the RX packet is a **new flow**. As such, EMU expects someone **listening** on that port. For this you need to use the https://github.com/cisco-system-traffic-generator/trex-emu/blob/39e9db9e881c2128e927c6842fe3b443f20566a3/src/emu/plugins/transport/client_ctx.go#L1201 function, and not the Dial.
Look at DNS Server here to see how to use the Listen function:
https://github.com/cisco-system-traffic-generator/trex-emu/blob/39e9db9e881c2128e927c6842fe3b443f20566a3/src/emu/plugins/dns/dns.go#L370

However, the real question is, are these meant to be new flows indeed? Since your plugin creates the requests these shouldn't be new flows, unless your DUT changes something in the packet (anything in the 5 tuple that defines a flow).

**Comment by hhaim** [comment]
@bdollma @janrodson 
from the bug description he try to create a simple UDP socket from each client **to** remote port 2123. 
the source port should have this property  ```(src_port & 0xff00 == 0xff00)``` .
Did you verify it? 

Every client could have up to 255 active UDP+TCP flows so there is no problem with one per each client. 

```
    name       | value 
    ----------------+------
    ft_new_udp      | 10    
    ft_new_no_cb*   | 10    
    dial            | 1     
    src_port_alloc  | 1     
    src_port_active | 1     
    ft_addv4        | 1     
    ft_activev4     | 1     
    ft_lookupv4     | 10  
```

From the counters I understand that there is **one** UDP flow active but the return answer does **not match** this. 
Please capture the traffic  in trex to verify it 

```
	ipv4 := layers.IPv4Header(p[ps.L3 : ps.L3+20])
	ver := ipv4.Version()
	if ver == 4 {
		var keyv4 c5tuplekeyv4
		if o.fillv4tuple(ps, &keyv4) != 0 {
			return -1
		}

		f, ok := o.ftv4[keyv4]
		o.flowTableStats.ft_lookupv4++
		if ok {  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< you should find the flow here ...
			o.flowTableStats.ft_lookup_foundv4++

```

**Comment by bdollma** [comment]
I suggest we close this due to lack of cooperation. 
The socket mechanism is proved to work in DNS plugin.

**Comment by bdollma** [comment]
Closed because lacks collaboration from the reporter.
