### ISSUE TITLE
issue with build

### ISSUE THREAD

**Issue by daratitus** [cisco-system-traffic-generator/trex-emu#2]
root@t-rex1:/home/trex-emu-2.84/src# go install -v cmd/trex-emu.go
cmd/trex-emu.go:14:2: cannot find package "github.com/akamensky/argparse" in any of:
        /usr/lib/go-1.10/src/github.com/akamensky/argparse (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/akamensky/argparse (from $GOPATH)
external/osamingo/jsonrpc/debug.go:7:2: cannot find package "github.com/alecthomas/jsonschema" in any of:
        /usr/lib/go-1.10/src/github.com/alecthomas/jsonschema (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/alecthomas/jsonschema (from $GOPATH)
emu/core/thread_ctx.go:13:2: cannot find package "github.com/go-playground/validator" in any of:
        /usr/lib/go-1.10/src/github.com/go-playground/validator (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/go-playground/validator (from $GOPATH)
external/osamingo/jsonrpc/context.go:6:2: cannot find package "github.com/intel-go/fastjson" in any of:
        /usr/lib/go-1.10/src/github.com/intel-go/fastjson (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/intel-go/fastjson (from $GOPATH)
emu/plugins/dot1x/mschapv2.go:27:2: cannot find package "golang.org/x/crypto/md4" in any of:
        /usr/lib/go-1.10/src/golang.org/x/crypto/md4 (from $GOROOT)
        /home/trex-emu-2.84/src/golang.org/x/crypto/md4 (from $GOPATH)
root@t-rex1:/home/trex-emu-2.84/src# cd ..
root@t-rex1:/home/trex-emu-2.84# ls
CONTRIBUTING.md  CONTRIBUTORS  LICENSE  README.asciidoc  VERSION  doc  external_share  scripts  src  unit-test
root@t-rex1:/home/trex-emu-2.84# cd scripts/
root@t-rex1:/home/trex-emu-2.84/scripts# ./utility_script build -v
cmd/trex-emu.go:14:2: cannot find package "github.com/akamensky/argparse" in any of:
        /usr/lib/go-1.10/src/github.com/akamensky/argparse (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/akamensky/argparse (from $GOPATH)
external/osamingo/jsonrpc/debug.go:7:2: cannot find package "github.com/alecthomas/jsonschema" in any of:
        /usr/lib/go-1.10/src/github.com/alecthomas/jsonschema (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/alecthomas/jsonschema (from $GOPATH)
emu/core/thread_ctx.go:13:2: cannot find package "github.com/go-playground/validator" in any of:
        /usr/lib/go-1.10/src/github.com/go-playground/validator (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/go-playground/validator (from $GOPATH)
external/osamingo/jsonrpc/context.go:6:2: cannot find package "github.com/intel-go/fastjson" in any of:
        /usr/lib/go-1.10/src/github.com/intel-go/fastjson (from $GOROOT)
        /home/trex-emu-2.84/src/github.com/intel-go/fastjson (from $GOPATH)
emu/plugins/dot1x/mschapv2.go:27:2: cannot find package "golang.org/x/crypto/md4" in any of:
        /usr/lib/go-1.10/src/golang.org/x/crypto/md4 (from $GOROOT)
        /home/trex-emu-2.84/src/golang.org/x/crypto/md4 (from $GOPATH)

**Comment by hhaim** [comment]
Try latest go version 1.14

**Comment by hhaim** [comment]
```go version go1.15.3 linux/amd64```
