### ISSUE TITLE
UnmarshalValidate doesn't work for slices.

### ISSUE THREAD

**Issue by besdollma** [cisco-system-traffic-generator/trex-emu#4]
The function [UnmarshalValidate](https://github.com/cisco-system-traffic-generator/trex-emu/blob/dc9507678474e4cf4f874a4ea5de0786c2cd6b50/src/emu/core/thread_ctx.go#L656) will fail validating slices, arrays or maps.
Take for example:

```
type Person struct {
      Name string      `json:"name" validate:"required"`
      Age     int      `json:"age" validate:"required"`
}
type PersonList struct {
       People []Person `json:"people" validate:"required"`
}

json := fastjson.RawMessage([]byte(`
{
    "people": [
           {
                  "name": "Bes",
                  "age": 25
           }
     ]
}`))
```
The data will be decoded successfully but when we attempt validating at `o.validate.Struct(v)`, we will fail.
This will happen even if we use the **"dive"** flag in validate.
Instead of using `o.validate.Struct(v)`, we should probably use `validate.Var(v, "dive")`.

This is a good reference from the validator package: https://github.com/go-playground/validator/issues/309

**Comment by bdollma** [comment]
Solved in f0d1cfb45ead1f5b1a72e566bd7b507357eef6db .
