### ISSUE TITLE
IPv6 parser unable to find RA option if preceded by PadN

### ISSUE THREAD

**Issue by hazem-hamed** [cisco-system-traffic-generator/trex-emu#5]
Reading the IPv6 parser code, looks like it’s expecting the RA option 2 bytes after the Hop-by-Hop header start.
```
     802  if p[l4+2] == 0x5 {
     803       // rounter alert
     804       ps.Flags |= IPV6_M_RTALERT_ML
     805  }
```
However, the NXOS MLD packet is inserting a 2-byte padding before the RA option, so it is actually 4-bytes into the header as follows:
```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |  Next Header  |  Hdr Ext Len  |          PadN option          |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                          RA option                            |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
The parser logic should first check the option code and skip any PadN or Pad1 options until it reaches the RA option.

**Comment by hhaim** [comment]
@hazem-hamed thanks for reporting. The ipv6 option code is broken. Will be fixed.
